traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/traefik-config/traefik.toml:/traefik.toml
    - $PWD/acme.json:/acme.json

machine:
  image: katacoda/docker-http-server
  labels:
    - "traefik.frontend.entryPoints=https"
    - "traefik.frontend.rule=Host:hello.hirsch.io"
