defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "test@traefik.io"
storage = "acme.json"

[[acme.domains]]
   main = "hirsch.io"
   sans = ["hello.hirsch.io", "dev.hirsch.io"]

[hirsch-io]
email = "ryan.hirsch@gmail.com"
storageFile = "hirsch-io.json"
onDemand = true
caServer = "http://172.18.0.1:4000/directory"
entryPoint = "https"

[[hirsch-io.domains]]
  main = "hello.hirsch.io"
