defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "Ryan.Hirsch@gmail.com"
storage = "acme.json"
onDemand = true
entryPoint = "https"

[[acme.domains]]
   main = "hirsch.io"
   sans = ["hello.hirsch.io", "dev.hirsch.io"]
